#!/usr/bin/env ruby

require "thor"
require "jast"

class JastCLI < Thor
  desc "schemas name property:type[:required] ...", "render all schema files"
  def schemas( name, *options)
    properties = {}
    required = []
    options.each do |opt|
      props = opt.split(":")
      properties[props[0].to_sym] = props[1]
      if props.size > 2
        required << props[0]
      end
    end
    generator = Jast::Generator.new
    generator.render_schemas name, properties, required
  end

end

JastCLI.start